### ISSUE TITLE
Visual Expressions Editor: two issues with animations that have blendshape values over 100

### ISSUE THREAD

**Issue by 64766C** [hai-vr/blendshape-viewer#4]
I have an avatar that requires a blink blendshape to be set to 110 for the eyes to actually be closed.

Animation that has a blendshape value 0 on the first frame and 110 on the second will break the bar used to change the blendshape value in the editor. The bar is replaced with just the text [0 : 110]:
![image](https://user-images.githubusercontent.com/100468852/159119109-1db5c79d-0c65-4d87-9a5f-d7ee32e69db4.png)

If you load a 2 frame animation where both frames have a blendshape value over a 100, the editor will silently change the values to 100 and will not allow setting values above 100. 

You could add a setting under advanced to allow blendshapes to have values over a 100 in the editor. That setting could be disabled by default but should be enabled automatically if an animation with a value over a 100 is loaded. When an animation with a blendshape value of over 100 is loaded, don't automatically change it to 100.

**Comment by hai-vr** [comment]
Hello, regarding this:
- The non-editable [0 : 110] is intentional, Visual Expressions Editor is not flexible enough to allow editing curves which keyframes have different values, so this displays a representation of the min-max range of keyframes values instead. The traditional animation editor must be used to edit these animations, at least in this version of the Visual Expressions Editor. I have plans for adding means of editing non-constant face expressions in a distant future.
- The "silently change" issue will be fixed in the next update.

I do have a question though, I had been told that animating a blendshape outside of the [0:100] range only works in editor, but not in-game where it's clamped.

Were you able to effectively confirm that your animation does work in-game with the 110 value?

**Comment by 64766C** [comment]
You are right of course. I assumed it worked outside the range because the original avatar creator had done it so and in unity there's a visible gap between the eyelids at 100. But I just tested it by setting a value to 200 with an animation and it was definitely clamped to 100 in game.

**Comment by hai-vr** [comment]
Hi, thank you for confirming so ⭐ 

Despite this I will fix the problem where the values are silently changed since this is not intentional.
